repos:
-   repo: local
    hooks:
    -   id: autopep8
        name: autopep8
        entry: autopep8 --in-place
        language: system
        types: [python]
        pass_filenames: true
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]