version: '3.7'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    command: ["./entrypoint.sh"]
    
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    
  db:
    image: ankane/pgvector:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
